name: send-tweet

on:
  workflow_dispatch:  # This allows manual triggering through GitHub Actions UI

jobs:
  tweet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm cache clean --force  # Clean npm cache to avoid corrupted packages
      - run: npm install --no-audit  # Install dependencies without audit to avoid errors
      - run: echo "${{ secrets.ENV_FILE }}" > .env  # Inject environment variables from secrets
      - run: node index.js  # Run the bot script to post the tweet
